### PR TITLE
Refactored to move FCA spreadsheet gen code into separate functions

### PR DESCRIPTION
**Pull request by dosumis**
To run as before - use FCA_spreadsheet_runner.py <path_to_fbbt.json>
FCA_spreadsheets.py now has functions that allow running from
iri_list, single_term or iri_list file.

Haven't yet added any additional tests.

Consider renaming FCA_spreadsheets.py to FCA_spreadsheet_tools.py

### CODE REVIEW

**Comment by dosumis** [comment]
@Clare72  - please review

**Comment by dosumis** [comment]
Some more notes on edit:

I tried to change as little code and functionality as possible.  I did do quite a bit of reformatting though so change might look more than they are.

**Comment by dosumis** [comment]
Working on some tests and tweaks.  Please don't merge yet.

**Comment by Clare72** [comment]
Made some edits to comments/docstrings and renamed FCA_spreadsheets.py as suggested - no edits to code.

**Comment by Clare72** [comment]
BTW, I seem to have already offered you admin access for FlyBase/flybase-ontology-scripts (says awaiting response).

**Comment by dosumis** [comment]
Tests now passing. Any questions about changes?

**Comment by Clare72** [comment]
I can still run it to make a spreadsheet, so working fine. I was previously thinking of going the other way and grabbing fbbt from github by default, rather than a user-defined local file, but this looks good. Thanks for tidying up.

**Comment by dosumis** [comment]
> I was previously thinking of going the other way and grabbing fbbt from github by default, rather than a user-defined local file, but this looks good. Thanks for tidying up.

Could add that as an optional keyword arg.

**Pull request merged**
